<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>Inmanta</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>Line comments</string>
        <key>begin</key>
        <string>\#</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.inmanta</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.hash.inmanta</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#docstrings</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Interpreted string literals</string>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.inmanta</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.inmanta</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.inmanta</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_placeholder</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Raw string literals</string>
        <key>begin</key>
        <string>`</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.inmanta</string>
          </dict>
        </dict>
        <key>end</key>
        <string>`</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.inmanta</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.raw.go</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_placeholder</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.import.inmanta</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.include.inmanta</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.as.inmanta</string>
          </dict>
        </dict>
        <key>match</key>
        <string>\b(?:(import)|(include)|(as))\b</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#brackets</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#special</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#storage_types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#language_variables</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\{|\}</string>
            <key>name</key>
            <string>punctuation.other.bracket.curly.inmanta</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\(|\)</string>
            <key>name</key>
            <string>punctuation.other.bracket.round.inmanta</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\[|\]</string>
            <key>name</key>
            <string>punctuation.other.bracket.square.inmanta</string>
          </dict>
        </array>
      </dict>
      <key>docstrings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(?=[uU]?[rR]?""")</string>
            <key>end</key>
            <string>(?&lt;=""")</string>
            <key>name</key>
            <string>comment.block.inmanta</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_quoted_double</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>special</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.inmanta</string>
            <key>match</key>
            <string>\\((0-7){3}|(x[a-fA-F0-9]{2})|(c\S)|([CM]-\S)|(M-C-\S)|.)</string>
          </dict>
        </array>
      </dict>
      <key>storage_types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\btypedef\b</string>
            <key>name</key>
            <string>storage.type.typedef.inmanta</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(implement|implementation)\b</string>
            <key>name</key>
            <string>storage.type.implement.inmanta</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bentity\b</string>
            <key>name</key>
            <string>storage.type.entity.inmanta</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bindex\b</string>
            <key>name</key>
            <string>storage.type.index.inmanta</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bend\b</string>
            <key>name</key>
            <string>storage.type.end.inmanta</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.inmanta</string>
            <key>match</key>
            <string>\b(using|extends|matching|parent|native)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.inmanta</string>
            <key>match</key>
            <string>\b(when|in|or|and|as|for|with|do)\b</string>
          </dict>
        </array>
      </dict>
      <key>string_escaped_char</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\([0-7]{3}|[abfnrtv\\'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8})</string>
            <key>name</key>
            <string>constant.character.escape.inmanta</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[^0-7xuUabfnrtv\'"]</string>
            <key>name</key>
            <string>invalid.illegal.unknown-escape.inmanta</string>
          </dict>
        </array>
      </dict>
      <key>string_placeholder</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>%(\[\d+\])?([\+#\-0\x20]{,2}((\d+|\*)?(\.?(\d+|\*|(\[\d+\])\*?)?(\[\d+\])?)?))?[vT%tbcdoqxXUbeEfFgGsp]</string>
            <key>name</key>
            <string>constant.other.placeholder.inmanta</string>
          </dict>
        </array>
      </dict>
      <key>language_variables</key>
      <dict>
        <key>match</key>
        <string>\b(self|cls)\b</string>
        <key>name</key>
        <string>variable.language.inmanta</string>
      </dict>
      <key>constants</key>
      <dict>
        <key>name</key>
        <string>constant.language.inmanta</string>
        <key>match</key>
        <string>\b(true|false)\b</string>
      </dict>
      <key>types</key>
      <dict>
        <key>name</key>
        <string>support.type.inmanta</string>
        <key>match</key>
        <string>\b(string|number|bool)\b</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.inmanta</string>
  </dict>
</plist>